### ISSUE TITLE
Indecisive food option

### ISSUE THREAD

**Issue by charlielafosse** [FAC-Sixteen/Week3-Magic3#20]
I'm sure this is something you've noticed, but when I make a food selection, it seems to ping about through a lot of different recipes and then eventually land on the appropriate one. Something worth addressing from a UI perspective

**Comment by tloth** [comment]
Some of us really enjoyed the roulette effect! But in certain cases, it never stops! (Relates #23)

**Comment by rymatech** [comment]
Hi Charlie, we did consider having not spin but decided to go with it. The app is searching through the object to find a food preference option which unfortunately takes time. If we didn't have the spinning, the user may think the app is not working properly. Perhaps we could look at how to speed up the search speed.
