### ISSUE TITLE
ES6 

### ISSUE THREAD

**Issue by charlielafosse** [FAC-Sixteen/Week3-Magic3#21]
Sweet ES6 m'dudes :+1: 

But just keep thinking about `let` and `const`... you use `let` quite a few times in your `script.js` when `const` would've done just fine. For example 

```
let a = document.getElementById('foodSelector');
```

Sure, you add an event listener to `a` on the next line, but you're not **reassigning** `a` at all.

A small point though!

**Comment by charlielafosse** [comment]
Oh and on another note... if you are going to use ES6, make sure you fully commit and don't slide between ES5 and ES6. Lines 53-54 in your `script.js`:

```
const url = 'https://www.themealdb.com/api/json/v1/1/random.php';
  var xhr = new XMLHttpRequest();
```

For best practices, try to agree as a group before you begin, if you're going to stick with ES5, or go all-out ES6.

**Comment by rymatech** [comment]
Thanks for pointing it out. We get very nervous with const. I have resolved the issue now.
