### ISSUE TITLE
Expand/Collapse container

### ISSUE THREAD

**Issue by baa1i** [FAC-Sixteen/Week3-Magic3#27]
Cool hover effect 👊 👊 👊 !!!
However would you consider making food-container and movie-container expand when clicked and collapse when clicked(there is no hover on mobile so the recipe won't show there ).

**Comment by aniablaziak** [comment]
In addition to the point above, I am unable to open both boxes at the same time, reading both the recipe and info on the film, it's either one or the other. This may be a bad user experience for some.

**Comment by sylv1ah** [comment]
Fixed!
