### ISSUE TITLE
movieAPI() function

### ISSUE THREAD

**Issue by charlielafosse** [FAC-Sixteen/Week3-Magic3#38]
Again, nice job on a successful XHR.

I've noticed, however, that the user input for movie genre has no bearing on what comes back in the API call. For instance, you could be scarring children for life:

![](http://i.imgur.com/zAJmQ4f.png)

Lool, just kidding. But it would be great to include `b.value` in the API request somehow?

**Comment by rymatech** [comment]
Thanks for pointing this out. It has now been sorted.

**Comment by RymaTech** [comment]
Thanks for pointing this out, the issue has now been resolved.
