### ISSUE TITLE
All in all...

### ISSUE THREAD

**Issue by charlielafosse** [FAC-Sixteen/Week3-Magic3#42]
Congratulations! :tada: y'all did great

You picked two awesome APIs that complement each other, you successfully made API calls and pulled the data onto the DOM, and to top it all off, made it look slick. Job complete :cactus: 

I also love the chaos of allowing the user to pick a genre such as 'Romance' and then just slinging them something random like Nicolas Cage's 'Lord of War'. That's hilarious.

![cage](https://media.giphy.com/media/CiTLZWskt7Fu/giphy.gif)

**Comment by rymatech** [comment]
Thanks Charlie @seabasshoang was responsible for the amazing CSS.
